### ISSUE TITLE
I can't change the language

### ISSUE THREAD

**Issue by Natalia-Oreiro** [portapps/phyrox-esr-portable#17]
when I set: "locale: cs"

each time the value is reset back to "locale: en-US"

What am I doing wrong ?

**Comment by crazy-max** [comment]
@Natalia-Oreiro Do you have renamed `phyrox-esr-portable.sample.yml` to `phyrox-esr-portable.yml` to as stipulated in the [documentation](https://portapps.io/doc/configuration/)?
