### ISSUE TITLE
policies.json

### ISSUE THREAD

**Issue by chorliya** [portapps/phyrox-esr-portable#18]
Where in `%systemdrive%\portapps\phyrox-esr-portable` can we use a `distribution\policies.json` which won't auto-reset on each run? 

Just to be clear, I have -unsuccessfully- gone through: 

- `https://portapps.io/app/phyrox-esr-portable/#policies`
- `https://portapps.io/doc/faq/`
- & everything within `https://github.com/portapps/phyrox-esr-portable` (as well as other versions)

I am unable to figure it out, been trying for a while now. Has anybody got a solution; or, any kind of help would be welcome, please, thanks! :) 

Here is an example policies.json that I use on a regular bases (many other things are set via about:config): 

`{
  "policies": {
    "CaptivePortal": false,
    "DisableAppUpdate": true,
    "DisableFeedbackCommands": true,
    "DisableFirefoxAccounts": true,
    "DisableFirefoxScreenshots": true,
    "DisableFirefoxStudies": true,
    "DisableForgetButton": true,
    "DisablePocket": true,
    "DisableProfileImport": true,
    "DisableProfileRefresh": true,
    "DisableSetDesktopBackground": true,
    "DisableSystemAddonUpdate": true,
    "DisableTelemetry": true,
    "Preferences": {
      "browser.cache.disk.enable": false,
      "browser.tabs.warnOnClose": true,
      "media.gmp-gmpopenh264.enabled": false,
      "media.gmp-widevinecdm.enabled": false,
      "network.IDN_show_punycode": true,
      "security.ssl.errorReporting.enabled": false
    },
    "PromptForDownloadLocation": true
  }
}`

And this is what `%systemdrive%\portapps\phyrox-esr-portable\app\distribution` defaults to on each run: 

`{
  "policies": {
    "DisableAppUpdate": true,
    "DontCheckDefaultBrowser": true
  }
}`

... So, what is there to be done .o0 

**EDIT**: Apologies if I've missed something, just can't get it for some reason.

**Comment by crazy-max** [comment]
Hi @chorliya,

You have to create the `data/policies.json` file like explained [here](https://portapps.io/app/phyrox-esr-portable/#policies). This file will be consumed and pushed to `app/distribution/policies.json`. If this is not the case, see your logs. Maybe your JSON file is malformed.
