### ISSUE TITLE
Update Firefox ESR to newer point release

### ISSUE THREAD

**Issue by 3oheicrw** [portapps/phyrox-esr-portable#35]
It's currently Firefox ESR 91.6.0. Phyrox ESR is lag behind at 91.5.0.

**Comment by the-big-nose** [comment]
> @3oheicrw As explained [on this page](https://portapps.io/doc/reporting-issue/), "We are aware of and notified of new application updates. So there’s no need to create an issue to update an application.". But feel free to open a PR.

Please update to 102.4.0esr, you are still at 102.3.0esr. Thanks.
