### ISSUE TITLE
Unpacking phyrox-esr-portable-win64-91.5.1-57.7z results in virus warning

### ISSUE THREAD

**Issue by SurinameClubcard** [portapps/phyrox-esr-portable#36]
Immediately after unpacking, I got this and the executable was quarantined. 

![afbeelding](https://user-images.githubusercontent.com/1786575/152589856-f34bb8a6-3311-459a-a82c-ee11b18ca75e.png)

**Comment by crazy-max** [comment]
Sometimes Antivirus scanner reports that a program is infected with a Virus or Trojan, even when the program is not really infected with any malicious code. This kind of problem is known as "False Positive". In other words, [Antivirus companies cause a big headache to small developers](http://blog.nirsoft.net/2009/05/17/antivirus-companies-cause-a-big-headache-to-small-developers/).

As stipulated in the [FAQ](https://portapps.io/doc/faq/#antivirus-complains-about-the-wrapper), those detections are generic. Most likely based on a heuristic detection and more prone to be false-positive and this [happens quite often](https://github.com/golang/go/issues?utf8=%E2%9C%93&q=is%3Aissue%20antivirus) with programs written in [Golang](https://golang.org/). The best you can do is to report this to your Antivirus software vendor as a false positive.

See also portapps/portapps#68 and https://github.com/search?q=org%3Aportapps+antivirus&type=Issues. Thanks for your support.
